define({
	"user": "Alpheios: User Diagram",
	"input": "Input text:",
	"lang": "Language:",
	"lang_grc": "Greek",
	"lang_la": "Latin",
	"lang_ar": "Arabic",
	"lang_got": "Gothic",
	"lang_chu": "Old Church Slavonic",
	"lang_en": "English",
	"fmt": "Format:",
	"fmt_aldt": "Ancient Language Dependency Treebank",
	"fmt_catib": "Columbia Arabic Treebank",
	"fmt_proiel": "PROIEL",
	"add": "Add",
	"edit": "Edit",
	"select": "Or select a previously saved sentence to edit:",
	"sequential": "Diagram words one at a time.",
	"direction": "Text Direction",
	"direction_ltr": "Left to Right",
	"direction_rtl": "Right to Left",
	"error_noinput":"Please input some text to diagram.",
	"error_nourl":"Configuration Error. The Diagram url has not been defined.",
	"error_noneselected":"Select a sentence to edit. ",
	"saved":"Changes saved."
});