define({
	"index-link":"&lt; Inflection Index",
	"links-label":"Switch Inflection: ",
	"link-noun":"%S declension",
	"link-adjective":"%S declension",
	"link-verb":"%S conjugation",
	"link-pronoun":"%S declension",
	"link-numeral":"%S declension",
	"link-article":"%S declension",
	"link-adverb":"%S declension",
	"title-verb":"Verb Conjugation",
	"title-noun":"Noun Declension",
	"title-adjective":"Adjective Declension",
	"title-article":"Article Declension",
	"title-pronoun-rel":"Relative Pronoun Declension",
	"title-pronoun-dem":"Demonstrative Pronoun Declension",
	"title-pronoun-pers":"Personal Pronoun Declension",
	"title-pronoun-inter":"Interrogative Pronoun Declension",
	"title-pronoun-indef":"Indefinite Pronoun Declension",
	"title-pronoun-refl":"Reflexive Pronoun Declension",
	"title-pronoun-recip":"Reciprocal Pronoun Declension",
	"title-pronoun-genrel":"General Relative Pronoun Declension",
	"title-pronoun-inten":"Intensive Pronoun Declension",
	"title-pronoun-pos":"Possessive Pronoun Declension",
	"title-pronoun-pos1":"Possessive Pronoun Declension (1st Person)",
	"title-pronoun-pos2":"Possessive Pronoun Declension (2nd Person)",
	"title-pronoun-pos3":"Possessive Pronoun Declension (3rd Person)",
	"title-cardinal":"Cardinal Declension",
	"title-numeral":"Numeral Declension",
	"title-verb-paradigms":"Verb Paradigms",
	"title-verb_imperative":"Verb Conjugation (Imperative)",
	"title-verb_infinitive":"Verb Conjugation (Infinitive)",
	"title-verb_gerundive":"Verb Conjugation (Gerundive)",
	"title-verb_participle":"Verb Participle ",
	"title-verb_supine":"Verb Conjugation (Supine)",
	"title-verb_irregular":"Verb Conjugation (Irregular)",
	"voice":"Voice",
	"tense":"Tense",
	"active":"Active",
	"middle":"Middle",
	"mediopassive":"Middle-Passive",
	"passive":"Passive",
	"conj":"Conjugation",
	"stem":"Stem",
	"mood":"Mood",
	"pers":"Person",
	"indicative":"Indicative",
	"subjunctive":"Subjunctive",
	"imperative":"Imperative",
	"infinitive":"Infinitive",
	"gerundive":"Gerund",
	"participle":"Participle",
	"verb_participle":"Participle",
	"supine":"Supine",
	"hdwd":"Lemma",
	"1st":"First",
	"2nd":"Second",
	"1st 2nd":"First/Second",
	"3rd":"Third",
	"4th":"Fourth",
	"singular":"Singular",
	"plural":"Plural",
	"dual":"Dual",
	"present":"Present",
	"perfect":"Perfect",
	"imperfect":"Imperfect",
	"future":"Future",
	"future_perfect":"Future Perfect",
	"future perfect":"Future Perfect",
	"pluperfect":"Pluperfect",
	"nominative":"Nominative",
	"genitive":"Genitive",
	"accusative":"Accusative",
	"aorist":"Aorist",
	"dative":"Dative",
	"ablative":"Ablative",
	"locative":"Locative",
	"vocative":"Vocative",
	"optative":"Optative",
	"masculine":"m.",
	"feminine":"f.",
	"masculine feminine":"m./f.",
	"masculine feminine neuter":"m./f./n.",
	"neuter":"n.",
	"full.masculine":"Masculine",
	"full.feminine":"Feminine",
	"full.masculine feminine":"Masculine/Feminine",
	"full.masculine feminine neuter":"Masculine/Feminine/Neuter",
	"full.neuter":"Neuter",
	"common":"Common",
	"decl":"Declension",
	"gend":"Gender",
	"num":"Number",
	"case":"Case",
	"expand":"+",
	"collapse":"-",
	"expand-tooltip":"More endings...",
	"collapse-tooltip":"Fewer endings...",
	"stem-classes":"Stem Characteristics (for Displayed Endings)",
	"disclaimer":"Please <a href=\"mailto:support@alpheios.net\">report</a> inaccurate or incomplete inflection data."
});