define({
	"inline_enable_cm": "Toggle Alpheios On",
 	"inline_disable_cm": "Toggle Alpheios Off",
 	"inline_cm_key": "m",
 	"inline_enable_tm": "Toggle Alpheios On",
 	"inline_disable_tm": "Toggle Alpheios Off",
	"inline_tm_key": "m",
	"decl_table_title": "Declension Table",
	"infl_window_title": "Inflections",
	"lang_menu": "Alpheios Language",
	"lang_none": "(none supported)",
	"view_label": "View",
	"view_tooltip": "Alpheios Browser Panels",
	"morph_toolbar_label": "Morphology",
	"morph_lookup_tooltip": "Enter a word or words.",
	"toolbar_grippy_tooltip": "Alpheios Toolbar",
	"toolbar_name": "Alpheios Toolbar",
	"toolbar_disable": "Hide Toolbar",
	"panel_detach": "Detach",
	"panel_close": "Close",
	"panel_options": "Options",
	"panel_trans_label": "Translation",
	"panel_trans_tab_external": "Internet",
	"panel_trans_tab_ped_primary": "Alpheios Pedagogical",
	"panel_trans_tab_external_url": "Enter URL of Translation",
	"panel_trans_opt_inter": "Interlinear Translation",
	"panel_trans_opt_inter_src": "In Source Text",
	"panel_trans_opt_inter_trans": "Show Interlinear Text",
	"help": "Help",
	"help_menuitem": "User Guide",
	"help_tooltip": "Open Alpheios User Guide",
	"version_string": "Beta Version",
	"vocab_toolbar_label": "Alpheios: Vocabulary",
		"inline_enable_cm":"Toggle Alpheios On",
		"inline_disable_cm":"Toggle Alpheios Off",
		"inline_enable_tm":"Toggle Alpheios On",
		"inline_disable_tm":"Toggle Alpheios Off",
		"loading_translation":"Loading translation for %S",
		"loading_grammar":"Loading Grammar",
		"loading_dictionary":"Loading Dictionary Window",
		"loading_inflect":"Loading Inflection Tables",
		"loading_speech":"Loading Audio",
		"loading_wordlist":"Checking Alpheios Wordlist...",
		"loading_misc":"Loading...",
		"loading_error":"Error Loading Requested Resource (%S)",
		"loading_interlinear":"Loading the interlinear translation...",
		"error_mhttpd_notfound":"Unable to find the local Alpheios mhttpd service and/or lexicon. ",
		"error_mhttpd_notstarted":"The local Alpheios mhttpd service startup may still be pending.  ",
		"error_mhttpd_failure":"The local Alpheios mhttpd service may not have been able to start.",
		"error_notranslation":"No translation available.",
		"error_request_interrupt":"Dictionary lookup interrupted.",
		"error_offline":"The browser may be in offline mode. If so, the Alpheios Tools will not function properly.\nTry toggling the status of 'Work Offline' in the browser's 'File' menu and then\ntoggling Alpheios Off and On again.",
		"decl_table_link":"Switch to %S declension",
		"short_definition":"Dictionary Definition",
		"error_nolanguages":"You must install an Alpheios language extension to use Alpheios.\nSee http://alpheios.net for instructions.",
		"error_getlanguages":"You must install an Alpheios language extension to use Alpheios.\n\nClick 'OK' for instructions.",
		"error_nolanguage_selected":"You must select a language to enable the Alpheios tools.\nAlpheios has not been enabled.",
		"error_nolexicon":"No valid lexicon defined for %S.",
		"tools":"Tools",
		"dictionary_link":"Define",
		"dictionary_window":"Alpheios Dictionary Browser",
		"inflect_link":"Inflect",
		"diagram_link":"Diagram",
		"speech_link":"Listen",
		"mywords_link":"Learned",
		"searching_dictionary":"Searching dictionary for %S.",
		"enable_interlinear":"Show Interlinear Translation",
		"inline_query_instruct":"Can you find the word(s) in the translated text panel on the right <br/>that corresponds to <span class=\"alph-inline-query-word\">%S</span>?",
		"inline_query_correct":"Correct",
		"inline_query_incorrect":"Incorrect: ",
		"info_tree_select":"Select a word to diagram.",
		"error_tree_notree":"No dependency diagram available for the selection.",
		"feedback_subject":"Alpheios Feedback ",
		"morph_form":"form",
		"morph_stem":"stem",
		"morph_prefix":"prefix",
		"morph_suffix":"suffix",
		"morph_pers":"person",
		"morph_num":"number",
		"morph_gend":"gender",
		"morph_gend_plural":"genders",
		"morph_tense":"tense",
		"morph_voice":"voice",
		"morph_case":"case",
		"morph_case_plural":"cases",
		"morph_dial":"dialect",
		"morph_dial_plural":"dialects",
		"morph_mood":"mood",
		"trigger_hint_mousemove_reader":"Look up a %S word by moving your mouse over it.",
		"trigger_hint_dblclick_reader":"Look up a  %S word by double-clicking on it.",
		"trigger_hint_mousemove_learner":"Access the quiz for a %S word by moving your mouse over it.",
		"trigger_hint_dblclick_learner":"Access the quiz for a  %S word by double-clicking on it.",
		"tree_trigger_hint_mousemove":"A word must be selected to produce a diagram. Move your mouse over a %S word to select a word to diagram.  ",
		"tree_trigger_hint_dblclick":"A word must be selected to produce a diagram. Double click on a %S word to select a word to diagram.",
		"tree_hint":"Mouse over words in sentence or tree to explore structure.",
		"vocab_hint":"",
		"version_link":"Beta Version",
		"align_nomatch":"No exact match.",
		"trans_reload":"Reloading...",
		"trigger_force_dbleclick":"Mouseover is disabled in Quiz Mode. Double-click to select a word.",
		"installed_versions":"Installed Alpheios Versions:",
		"browse_backup_file":"Select Alpheios Data Backup File",
		"browse_restore_file":"Select Alpheios Data Restore File",
		"browse_backup_folder":"Select Backup Folder for Alpheios Data",
		"confirm_dialog":"Alpheios: Confirm Action",
		"warning_dialog":"Alpheios: Warning",
		"datamanager_configure":"Click OK to configure the Alpheios user data services,\nor Cancel to proceed with user data features disabled.",
		"datamanager_disabled":"The Alpheios user data features have been disabled.",
		"restore_confirm":"Click OK to restore the Alpheios user data now,\nor Cancel to proceed without user data features enabled.",
		"restore_failed":"Restoration of Alpheios user data failed.\nThe Alpheios user data features have been disabled.",
		"backup_inprogress":"Backing Up Alpheios Data...",
		"restore_inprogress":"Restoring Alpheios Data...",
		"datamanager_confirm_newuser":"No restore file selected, or restore failed.\nClick OK to start fresh as a new user,\n or Cancel to proceed with user data features disabled.",
		"general_dialog_title":"Alpheios",
		"mywords_added":"Add %S to your list of known words?",
		"error_toolbar_disable":"Use View/Toolbars to re-enable the Alpheios toolbar.",
		"backup_success":"Data Backup Complete.",
		"backup_failed":"Data Backup Failed.",
		"restore_failed_nodisable":"Data Restore Failed. ",
		"restore_success":"Data Restore Complete.",
		"clear_success":"Data Cleared.",
		"clear_failed":"Failure Clearing Data.",
		"vocab_wordlist_header":"My %S Word List",
		"vocablist_header":"Vocabulary for %S",
		"vocablist_pofs_select":"Part of Speech:",
		"vocab_wordlist_hints":"Checked words have been learned.",
		"vocab_wordlist_xml":"Export as XML ",
		"vocab_wordlist_all":"Show All ",
		"vocab_wordlist_unlearned":"Hide Learned",
		"vocab_wordlist_learned":"Show Only Learned ",
		"select_language_title":"Alpheios: Select Language",
		"select_language_text":"Select the language for the page:",
		"xml_export_title":"Save As",
		"dictionary_browse_link":"Browse Dictionary",
		"dictionary_browse_root_link":"Browse To %S",
		"dict-toolbar-label": "Full Definition",
		"panel.dict.menu":"Change Dictionary",
		"panel.dict.none":"None (Short Definitions Only)",
		"panel.dict.browse": "Browse Dictionary"	
});