define({
	"menu": "Alpheios",
	"options": "Options",
	"options_tooltip": "Configure Alpheios Preferences",
	"feedback": "Send Feedback",
	"feedback_tooltip": "Email Feedback on Alpheios",
	"about": "About",
	"about_tooltip": "About Alpheios",
	"site": "Alpheios Home",
	"site_tooltip": "Open the net site",
	"lang": "Language",
	"lang_tooltip": "Select Language for Alpheios",
	"level_reader": "Reading Mode",
	"level_reader_tooltip": "Alpheios Reading Mode",
	"level_learner": "Quiz Mode",
	"level_learner_tooltip": "Alpheios Quiz Mode",
	"backup": "Backup Data",
	"backup_tooltip": "Backup Data Now",
	"restore": "Restore Data",
	"restore_tooltip": "Restore Data Now",
	"clear": "Clear Data",
	"clear_tooltip": "Clear Data Now",
	"wordlist": "Word List",
	"wordlist_tooltip": "See My Word List",
	"user_diagram": "Diagram Sentence",
	"user_diagram_tooltip": "Sentence Diagrams Tool",
	"user_align": "Align Translation",
	"user_align_tooltip": "Translation Alignment Tool",
	"userdata": "User Data",
	"userdata_tooltip": "User Data Functions" 
});