define({
	"preferences": "Alpheios Preferences",
	"toolbar": "Toolbar",
	"mouse": "Mouse Settings",
	"advanced": "Advanced",
	"advanced_label": "Advanced...",
	"customize_label": "Customize...",
	"customize_accesskey": "c",
	"features": "General",
	"log_level": "Console Log Level",
	"log_level_fatal": "Fatal",
	"log_level_error": "Error",
	"log_level_warn": "Warn",
	"log_level_info": "Info",
	"log_level_config": "Config",
	"log_level_debug": "Debug",
	"log_level_trace": "Trace",
	"log_level_all": "All",
	"includecontext": "Extract Surrounding Context From Word",
	"popuptrigger": "Mouse action to trigger lookup:",
	"popuptrigger_default": "Default mouse action for lookup:",
	"popuptrigger_mousemove": "mousemove",
	"popuptrigger_dblclick": "dblclick",
	"windows": "Window and Panel Preferences",
	"windows_label": "Window/Panel Settings...",
	"grammar_window_loc": "Grammar Window Location",
	"shift_window_loc": "Shift Key Window Location",
	"top_left": "Top Left",
	"top_right": "Top Right",
	"bottom_left": "Bottom Left",
	"bottom_right": "Bottom Right",
	"default_language": "Preferred Language",
	"panels_default": "Panel Defaults",
	"panels_restore_defaults": "Restore Defaults",
	"panels_sticky": "Interface Changes Sticky",
	"panel_name": "Panel Name",
	"panel_ped": "Enhanced",
	"panel_basic": "Basic",
	"panel_morph": "Morphology Panel",
	"panel_dict": "Dictionary Panel",
	"panel_trans": "Translation Panel",
	"panel_tree": "Dependency Tree Panel",
	"panel_vocab": "Vocabulary Panel",
	"panel_etym": "Etymology/Cognates Panel",
	"dictionaries": "Dictionaries",
	"dictionaries_advanced": "Advanced Dictionary Settings",
	"lookup": "Word Lookup",
	"toolbar_enable": "Enable Alpheios Toolbar",
	"toolbar_lookup": "Enable Toolbar Lookup",
	"panels_inline": "Inline Panels",
	"panels_default_caption": "Panels Open By Default",
	"services_advanced": "Advanced Service Settings",
	"advanced_accesskey": "a",
	"interlinear": "Interlinear Translation",
	"interlinear_enable": "Enable Interlinear Translation (Alpheios Enhanced Texts only) EXPERIMENTAL",
	"popuptrigger_mousemove": "mousemove",
	"popuptrigger_dblclick": "dblclick",
	"timeouts_default": "Default Request Timeouts",
	"defaults_misc": "Miscellaneous Defaults",
	"dict_full_timeout": "Full Dictionary Request Timeout (ms):",
	"smallicons": "Use Small Icons in Popup",
	"speech": "Enable Listen Icon in Popup",
	"mhttpd_host": "Local mhttpd hostname:",
	"mhttpd_port": "Local mhttpd port:",
	"morphservice_remote": "Use Remote Morphology Service:",
	"morphservice_remote_url": "Remote Morphology Service Url:",
	"sites_label": "Enabled Sites...",
	"sites": "Alpheios-Enabled Sites",
	"sites_accesskey": "s",
	"userdata": "User Profile",
	"userdata_advanced": "Alpheios User Profile - Advanced",
	"userdata_service": "Data Storage Service:",
	"userdata_service_none": "&lt;none&gt;",
	"backup_options": "Backup/Restore Options",
	"backup_enable": "Enable Data Backup?",
	"backup_interval": "Backup Interval:",
	"backup_interval_lookup": "After X User Data Additions",
	"backup_interval_disable": "Whenever Alpheios is Disabled",
	"backup_interval_appquit": "Whenever Firefox Is Closed",
	"backup_interval_request": "On Request Only",
	"backup_interval_lookup_num": "Backup After How Many User Data Additions?",
	"backup_keep": "Number of Backups to Keep:",
	"restore_enable": "Enable Data Restore?",
	"restore_interval": "Restore Interval:",
	"restore_interval_enable": "Whenever Alpheios is Enabled",
	"restore_interval_appstart": "Whenever Firefox is Started",
	"restore_interval_request": "On Request Only",
	"restore_confirm": "Require confirmation before restore?",
	"backup_local_file": "Backup File Path:",
	"restore_local_file": "Restore File Path:",
	"file_browse": "Browse...",
	"userdata_service_local": "Local Zip File",
	"clear_interval": "Clear User Data:",
	"userdata_model": "Alpheios User Profile:",
	"userdata_model_ffprofile": "Single User Per Firefox Profile (No backup or restore)",
	"userdata_model_ffprofileplus": "Single User Per Firefox Profile",
	"userdata_model_shared": "Multiple Users per Firefox Profile",
	"userdata_model_custom": "Custom",
	"userdata_model_custom_info": "(Configure Custom User Data Storage Settings Below)",
	"userdata_model_disable": "User Features Disabled",
	"backup_to_restore": "Backup and Restore to/from same file?",
	"dict_default":"Default Dictionary:",
	"dict_none":"None (Short Definitions Only)",
	"dict_url_search":"Search URL:",
	"dict_url_lemma_param":"Lemma Parameter:",
	"dict_url_id_param":"Lemma ID Parameter:",
	"dict_url_multiple_lemmas":"Multiple Words Per Request",
	"dict_url_browse_url":"Browse URL:",
	"dict_buttons_moveup":"Move Up",
	"dict_buttons_movedown":"Move Down",
	"dict_labels_order_short":"Dictionary search order for short definitions:",
	"dict_labels_order_full":"Dictionary search order for full definitions:",
	"dict_buttons_copy_full":"Reset From Short Definitions",
	"dict_buttons_copy_short":"Reset From Full Definitions",
	"dict_buttons_advanced":"Advanced...",
	"dict_labels_single_full":"Full Definitions Dictionary: %S",
	"dict_labels_single_short":"Short Definitions Dictionary: %S",
	"nolanguages":"Alpheios Language Tool extensions are required for this feature.    ",
	"sites_buttons_disable":"Disable",
	"sites_buttons_enable":"Enable",
	"site_labels_autoenable":"Sites for which Alpheios can be auto-enabled:",
	"trigger_mousemove":"mousemove",
	"trigger_dblclick":"dblclick",
	"url_morph":"Morphology Service URL:",
	"url_morph_request":"Morphology Service Request Parameters:",
	"url_morph_timeout":"Morphology Service Timeout (ms):",
	"panels_use_defaults":"Use Global Defaults",
	"panels_restore_defaults":"Restore Defaults"
});